-- 코드를 입력하세요
WITH TOTAL AS (SELECT ONLINE_SALE_ID,USER_ID,PRODUCT_ID,SALES_AMOUNT,SALES_DATE FROM ONLINE_SALE
UNION  
SELECT OFFLINE_SALE_ID,NULL,PRODUCT_ID,SALES_AMOUNT,SALES_DATE FROM OFFLINE_SALE)
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT FROM TOTAL
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY SALES_DATE, PRODUCT_ID,USER_ID