

WITH R AS (
    SELECT MEMBER_ID,COUNT(*) CNT, RANK() OVER(ORDER BY COUNT(*)DESC) R_RANK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RR
INNER JOIN MEMBER_PROFILE M
ON RR.MEMBER_ID = M.MEMBER_ID
WHERE M.MEMBER_ID IN (SELECT MEMBER_ID FROM R WHERE R_RANK = 1)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT